// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAshBm_Y163aY8_N_4yHlW58I6Mvj9TubA',
    appId: '1:849228480283:web:9c5b6f37a1dac8d2fa9dbe',
    messagingSenderId: '849228480283',
    projectId: 'climateirrigationapp',
    authDomain: 'climateirrigationapp.firebaseapp.com',
    databaseURL: 'https://climateirrigationapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'climateirrigationapp.firebasestorage.app',
    measurementId: 'G-CJ31XW5Q33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlnaEqlPWmb3E99qRhd-Hap1XlaStdjAM',
    appId: '1:849228480283:android:92f1797e95884072fa9dbe',
    messagingSenderId: '849228480283',
    projectId: 'climateirrigationapp',
    databaseURL: 'https://climateirrigationapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'climateirrigationapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjYo1ajkSMe3zghjWeaP1n0RG5iqxo5JM',
    appId: '1:849228480283:ios:70891784c45f480ffa9dbe',
    messagingSenderId: '849228480283',
    projectId: 'climateirrigationapp',
    databaseURL: 'https://climateirrigationapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'climateirrigationapp.firebasestorage.app',
    iosBundleId: 'com.example.climateResponsiveIotIrrigationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjYo1ajkSMe3zghjWeaP1n0RG5iqxo5JM',
    appId: '1:849228480283:ios:70891784c45f480ffa9dbe',
    messagingSenderId: '849228480283',
    projectId: 'climateirrigationapp',
    databaseURL: 'https://climateirrigationapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'climateirrigationapp.firebasestorage.app',
    iosBundleId: 'com.example.climateResponsiveIotIrrigationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAshBm_Y163aY8_N_4yHlW58I6Mvj9TubA',
    appId: '1:849228480283:web:6164f0b0388f2a0dfa9dbe',
    messagingSenderId: '849228480283',
    projectId: 'climateirrigationapp',
    authDomain: 'climateirrigationapp.firebaseapp.com',
    databaseURL: 'https://climateirrigationapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'climateirrigationapp.firebasestorage.app',
    measurementId: 'G-PZ9LFE9W91',
  );
}
